export const ErrorEnum = Object.freeze({
    notLogged: {error: 'notLogged', reason: 'You are not logged in'},
    profileNotSelected: {error: 'profileNotSelected', reason: 'You did not select profile'},
    notAuthorized: {error: 'notAuthorized', reason: 'You are not authorized'},
    userNotFound: {error: 'userNotFound', reason: 'User not found'},
    firstNameError: {error: 'firstNameError', reason: 'Enter valid first name'},
    lastNameError: {error: 'lastNameError', reason: 'Enter valid last name'},
    validUsernameError: {error: 'usernameError', reason: 'Enter valid username'},
    existsUsernameError: {error: 'usernameError', reason: 'Username already exists'},
    notExistsUsernameError: {error: 'usernameError', reason: 'Username does not exists'},
    validEmailError: {error: 'emailError', reason: 'Enter valid email'},
    existsEmailError: {error: 'emailError', reason: 'Email already exists'},
    notExistsEmailError: {error: 'emailError', reason: 'Email does not exists'},
    phoneNumberError: {error: 'phoneNumberError', reason: 'Enter valid phone number'},
    validPassword: {error: 'passwordError', reason: 'Enter valid password'},
    passwordMatch: {error: 'passwordError', reason: 'Passwords do not match'},
    userId: {error: 'userId', reason: 'User id did not found'},
    userNotValidatedError: {error: 'userNotValidatedError', reason: 'Your profile is not validate. Please check your email.'},
    numberOfValidationEmailSentError: {error: 'numberOfValidationEmailSentError', reason: 'Validation email sent limit'},
    proxyError: {error: 'proxyError', reason: 'No available proxies, please contact admin'},
    numberError: {error: 'numberError', reason: 'Please enter valid number'},
    validInstagramTokenError: {error: 'instagramTokenError', reason: 'Token is not valid'},
    expiredInstagramTokenError: {error: 'instagramTokenError', reason: 'Token expired'},
    boolError: {error: 'boolError', reason: 'It\'s not boolean.'},
    notValidProfile: {error: 'notValidProfile', reason: 'Profile is not valid'},
    timeError: {error: 'notValidTime', reason: 'Enter valid time'},
    dropdownError: {error: 'dropdownError', reason: 'Not allowed value selected'},
    instagramProfilePicError: {error: 'instagramProfilePicError', reason: 'Picture path is not valid'},
    sessionProxyError: {error: 'sessionProxyError', reason: 'Session proxy does not mach database proxy'},
    userGroupNameError: {error: 'userGroupNameError', reason: 'Enter valid user group name'},
    messageError: {error: 'messageError', reason: 'Enter valid messages'},
    userGroupError: {error: 'userGroupError', reason: 'Not valid group'},
    dateTimeError: {error: 'notValidDate', reason: 'Enter valid date'},
    captionTextError: {error: 'captionTextError', reason: 'Enter valid caption text'},
    notValidFile: {error: 'notValidFile', reason: 'File is not valid'},
    reachMaxUserGroupMembers: {error: 'reachMaxUserGroupMembers', reason: '20 is max members in group'},
    userGroupExists: {error: 'userGroupExists', reason: 'Group with that name already exists'},
    userGroupMemberExists: {error: 'userGroupMemberExists', reason: 'User already exists'},
    maxNumberOfTargetError: {error: 'maxNumberOfTargetError', reason: 'You can not have more than 10 targets'},
    profileExpired: {error: 'profileExpired', reason: 'Profile expired'},
    messageLenghtError: {error: 'messageLenghtError', reason: 'Max characters in message is 500'},
    captionTextLengthError: {error: 'captionTextLengthError', reason: 'Max characters in caption text is 2200'},
    captionTextHashTagError: {error: 'captionTextHashTagError', reason: 'Max number of has tags is 30'},
    instagramProfileAlreadyExistsError: {error: 'instagramProfileAlreadyExistsError', reason: 'Profile already exists on our platform'},
    dateError: {error: 'dateError', reason: 'Not valid date'},
    selectedStatisticsTypeError: {error: 'selectedStatisticsType', reason: 'Not valid statistics type'},
    noStatisticsRecord: {error: 'noStatisticsRecord', reason: 'No record for this date'},
    timeZoneError: {error: 'notValidTimeZone', reason: 'Not valid time zone'},
    periodError: {error: 'periodError', reason: 'Not valid days'},
    freeTrailError: {error: 'freeTrailError', reason: 'Free trail expired for this profile. Please contact admin if you want to extend days'},
    numberOfFollowersError: {error: 'numberOfFollowersError', reason: 'You can not login profile with more than 25k followers'},
});
